### PR TITLE
Make editor easier to scroll, but lock element preview at top

### LINKED ISSUE #692: Improve scrolling of element editor views
At least two improvements are possible: 
- fix the preview to the top of the view. scroll attribute UI up behind it. 
- improve touch/scroll behavior. currently, a swipe-to-scroll often fails when it starts on a slider or element that might have a different interpretation of the swipe. We're certainly not the only app to encounter this ... must be design or code methods to improve this.

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #692

### CODE REVIEW

**Comment by gvn** [comment]
This is awesome. Feels so much better!

One thing: seems like the scrubber should go all the way to the top and bottom. Right now there's some space around it (~10px top & ~20px bottom). Thoughts @vazquez ?

**Comment by vazquez** [comment]
Let me take a look on my device, will comment in a few

**Comment by alanmoo** [comment]
I can see that, though this way I feel like you know you're at the top/bottom because it ends.

**Comment by gvn** [comment]
Yeah, although if the view gets much taller it will end prematurely because it doesn't repeat-y.

**Comment by vazquez** [comment]
Right, I see what you're referring to. Both of you have good points. I personally like the scrubber going all the way down and all the way up (no margin). It's more skeumorphic that way; it represents more accurately what you see in real life. (music scrubbers being the point of reference here)

**Comment by alanmoo** [comment]
Repeat-y isn't explicitly set, but that's what it's doing...take a look at the image

**Comment by alanmoo** [comment]
Take a look at it now

**Comment by vazquez** [comment]
Ooo looking nice! :dancers:

**Comment by gvn** [comment]
Looks great! R+

**Pull request closed without merging**
