### PR TITLE
adding eslint; removing jsxhint

### LINKED ISSUE #429: JSHint is overlooking global var creation
It seems that JSHint isn't catching global vars being used (at least in `/src/pages/page/loader.js`).

### PR DESCRIPTION
**Pull request by gvn**
Resolves #429

### CODE REVIEW

**Comment by gvn** [comment]
I've set a lot of rules to only throw warnings so that we don't have to touch any existing code. I figure we can slowly roll these rules over to be required one at a time to avoid a huge refactor.

I also have excluded our `tests` directory for the moment and `src/static/js/Intl.js` which is something we should probably include as a module instead of adding directly to the repo.

There is 1 error that I think we should resolve:

```
src/lib/validators.js
  90:50  error  Unexpected token =>
```

I'm not super clear on what this code is doing exactly. Any thoughts?

**Comment by k88hudson** [comment]
The validators are for the login stuff (i.e. password/email validators). Weird that it's throwing that error... is es6 not being parsed properly or something?

As for Intl.js, I think it's probably fine to always exclude `src/static` anyway, although the reason that is there is that it can't be loaded with webpack (I think there's a ticket open to fix it, but yeah)

**Comment by k88hudson** [comment]
Let me know if you need help figuring any of that out

**Comment by gvn** [comment]
I guess that arrow function just needed to be wrapped in some parens. ES6 is turned on in the `env` inside the `.eslintrc`, so should work quite well with our code!

**Pull request merged**
