### PR TITLE
[#386] Restore zoom out button for edit mode

### PR DESCRIPTION
**Pull request by k88hudson**
Just fixing a small ux regression

### CODE REVIEW

**Comment by k88hudson** [comment]
@gvn R?

**Comment by gvn** [comment]
Might wanna run that svg through svgo.

**Comment by k88hudson** [comment]
I think there was a problem with optimizing the original or something, it's literally a copy of the other one with the colours changed

**Comment by gvn** [comment]
Ok...nbd. :+1:

**Comment by gvn** [comment]
R+

**Pull request merged**
