### PR TITLE
Adding infinite scroll to Discover view

### LINKED ISSUE #153: Implement infinite scrolling / pagination for list views
This issue has been migrated from mozilla/webmaker-android#2035.

It was originally written by [thisandagain](https://api.github.com/users/thisandagain) on Thu May 28 2015 and had the following description:

> List views are currently limited to the first "page" of results. We need to implement something like https://www.npmjs.com/package/react-infinite-scroll to allow us to render all results.

On Thu May 28 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Leaning towards https://github.com/seatgeek/react-infinite for implementation but flagging that I'm not seeing any mature / great performing options for react. To be fair, this is a hard problem that Android doesn't even deal with well natively (iOS's `UICollectionView` API is the benchmark here IMO).

On Mon Jun 29 2015, [Pomax](https://api.github.com/users/Pomax) commented:

> Do have to point out how annoying infinite lists are because it becomes impossible to jump back to "that one cool project you say an indeterminate amount of scrolling ago". I'd urge us to consider pagination, or at the very least infinite scroll with soft-pagination.

On Mon Jun 29 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Not sure I follow **@****Pomax** . 100% agreed in browser context, but do you have any examples of native mobile apps on Android that don't infinitely scroll infinite lists? Instagram does when it detects that you are on 2G but that's about all I can think of.

On Mon Jun 29 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> **@****Pomax** - keep in mind that future social features will make it easier to find things you found before (via profiles, likes, comment notifications, etc).

### PR DESCRIPTION
**Pull request by gvn**
Closes #153

### CODE REVIEW

**Comment by xmatthewx** [comment]
Wondering how this will impact people with limited or costly data. Does it require a firm pull to load more? Or, is it triggered passively at the bottom of the view? Can this be configured?

**Comment by gvn** [comment]
Not sure what you mean by a firm pull, but this is like Instagram where more stuff loads when you hit the bottom.

**Comment by k88hudson** [comment]
Looks good to me! R+

I think @xmatthewx is talking about pull-to-refresh, which would be a slightly different pattern that what's implemented here.

I think pull-to-refresh makes sense to surface newer content in a real-time context/feed, e.g. Twitter. In this case, since additional content is older, not newer, infinite scroll probably makes more sense, but definitely could be up for discussion depending on what you're going for.

**Comment by gvn** [comment]
I don't think we have enough fresh content to justify adding pull to refresh right now. To me this implementation makes sense and feels consistent with how most apps with content feeds work.

I don't think the bandwidth impact will be substantial. The thumbnails are about 20KB each. A lot of web pages are easily 500-1000KB these days.

**Comment by gvn** [comment]
Per discussion: Load next 5 and randomize order.

**Pull request merged**
