### PR TITLE
logging project views

### PR DESCRIPTION
**Pull request by gvn**
Closes: #942

### CODE REVIEW

**Comment by alanmoo** [comment]
I don't have a way to confirm this works, but from this side the code LGTM...

**Comment by gvn** [comment]
Basically you can look at the network activity and see it got an "ok" response, but beyond that I dunno...

**Comment by alanmoo** [comment]
Well, considering that testing it in Postman gives a 401 and testing it on device gives a 200, I'll say this looks good.

**Comment by gvn** [comment]
Cool. Yeah, you gotta do it in app so that it's an authenticated request. :+1:

**Pull request merged**
