### PR TITLE
Add filter for discovery page

### LINKED ISSUE #304: Add locale filter to discover gallery
Using API enhancements from https://github.com/mozilla/api.webmaker.org/issues/121, let's fill the discover gallery with content specific to the user's locale first (and backfill with en-US where necessary).

@xmatthewx putting this in 1.0.2, but feel free to push.

cc @HPaulJohnson

### PR DESCRIPTION
**Pull request by alicoding**
Fixes #304

This patch added the implementation of filtered locale discovery page
I've also added id-ID translation file and move i18n related stuff into
its own file.

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron r?

**Comment by secretrobotron** [comment]
Just going to wait for https://github.com/mozilla/api.webmaker.org/pull/135 to land so we can test.

**Comment by secretrobotron** [comment]
Fixes #304.

**Comment by secretrobotron** [comment]
@gvn are you able to R this?

**Comment by k88hudson** [comment]
Ok looks fine to me, the only thing to keep in mind is to leave the `/discover` route around in the API in order to still support old clients

**Comment by secretrobotron** [comment]
@k88hudson :+1: it's still there. @cadecairos and I were careful to leave it alone.

**Comment by k88hudson** [comment]
awesome thanks!

**Pull request merged**
