### PR TITLE
fixes page highlights in project view when picking link destinations

### LINKED ISSUE #522: When Setting a Destination for the Button Element, I'm not shown what page I'm currently on.
This is the view I see when setting the button destination right now...

image

It's supposed to indicate which page the button is on currently, but doesn't.
These are the only two pages in my project.

### PR DESCRIPTION
**Pull request by Pomax**
fixes https://github.com/mozilla/webmaker-core/issues/522

### CODE REVIEW

**Comment by gvn** [comment]
R+

I wonder if we should consider a landing this due to it being a bugfix. Thoughts @thisandagain @xmatthewx @k88hudson ?

If we do, let's run through all our QA scripts again before merging...

**Comment by gvn** [comment]
I ran through: https://github.com/mozilla/webmaker-core/issues/496 and everything is still the same with this patch.

**Comment by gvn** [comment]
https://github.com/mozilla/webmaker-core/issues/495 also checks out fine (although I noticed it mentions corner radius on images, which I don't think ever existed?).

**Comment by Pomax** [comment]
I ran through https://github.com/mozilla/webmaker-core/issues/494 and didn't find anything regressed (although I did find one more issue that has nothing to do with this PR or files it touches)

**Comment by gvn** [comment]
I feel good about landing this...

m3y1mo6

**Comment by thisandagain** [comment]
R+

**Pull request merged**
