### PR TITLE
Make icons in text-style white when selected

### LINKED ISSUE #701: Text style "checkbox" labels should be white when active
When "text style" elements are active, the `B`,`I`, and `U` elements should be white like the text alignment elements are in the following image. Currently they stay dark.

text styles

### PR DESCRIPTION
**Pull request by alanmoo**
Closes #701. It's not the greatest implementation, but I think it's the right balance of ease vs complexity for now. Might want to revisit the approach if we use this component more.

### CODE REVIEW

**Comment by vazquez** [comment]
YES YES YES YES YES YES YES YES YES

**Comment by gvn** [comment]
This is close. The problem is that when you return to editing formatted text the coloring is wrong on the highlighted button(s).

STR: 
1. edit text
2. make it bold
3. return to "Page" view
4. edit same text 
5. see that the **B** is black

**Comment by alanmoo** [comment]
Ok, let's try this now. Changed the state management a bit to make it easier to check on component load.

**Comment by gvn** [comment]
WFM R+ :zap:

**Pull request closed without merging**
